server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizwebdb
    username: postgres
    password: Stark@1945

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 86400000